"""Tests for zeek_parser.py — log parsing, filtering, and summarization.

Each function in zeek_parser is tested with realistic Zeek TSV data
generated by the conftest fixtures.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from zeek_parser import (
    filter_log,
    get_connections_summary,
    get_log_summary,
    parse_all_logs,
    parse_zeek_log,
)


# ---------------------------------------------------------------------------
# parse_zeek_log
# ---------------------------------------------------------------------------


class TestParseZeekLog:
    def test_parse_conn_log(self, analysis_dir: Path):
        """Parses conn.log and returns list of dicts with correct fields."""
        rows = parse_zeek_log(str(analysis_dir / "conn.log"))
        assert len(rows) == 3
        assert rows[0]["id.orig_h"] == "192.168.1.10"
        assert rows[0]["id.resp_h"] == "10.0.0.1"
        assert rows[0]["proto"] == "tcp"

    def test_parse_dns_log(self, analysis_dir: Path):
        """Parses dns.log and returns correct query data."""
        rows = parse_zeek_log(str(analysis_dir / "dns.log"))
        assert len(rows) == 2
        assert rows[0]["query"] == "example.com"
        assert rows[1]["rcode_name"] == "NXDOMAIN"

    def test_parse_http_log(self, analysis_dir: Path):
        """Parses http.log with method and URI fields."""
        rows = parse_zeek_log(str(analysis_dir / "http.log"))
        assert len(rows) == 1
        assert rows[0]["method"] == "GET"
        assert rows[0]["host"] == "example.com"
        assert rows[0]["uri"] == "/index.html"

    def test_parse_with_limit(self, analysis_dir: Path):
        """Limit parameter restricts number of returned rows."""
        rows = parse_zeek_log(str(analysis_dir / "conn.log"), limit=2)
        assert len(rows) == 2

    def test_parse_limit_zero_returns_all(self, analysis_dir: Path):
        """Limit=0 returns all rows."""
        rows = parse_zeek_log(str(analysis_dir / "conn.log"), limit=0)
        assert len(rows) == 3

    def test_parse_empty_log(self, empty_analysis_dir: Path):
        """Log with only headers and no data rows returns empty list."""
        rows = parse_zeek_log(str(empty_analysis_dir / "empty.log"))
        assert rows == []

    def test_parse_file_not_found(self):
        """Missing file raises FileNotFoundError."""
        with pytest.raises(FileNotFoundError):
            parse_zeek_log("/nonexistent/path/conn.log")

    def test_fields_preserved(self, analysis_dir: Path):
        """All field names from #fields line are present as keys."""
        rows = parse_zeek_log(str(analysis_dir / "conn.log"))
        expected_fields = {
            "ts",
            "uid",
            "id.orig_h",
            "id.orig_p",
            "id.resp_h",
            "id.resp_p",
            "proto",
            "service",
            "duration",
            "orig_bytes",
            "resp_bytes",
            "conn_state",
            "history",
        }
        assert set(rows[0].keys()) == expected_fields

    def test_notice_log_parsed(self, analysis_dir_with_notices: Path):
        """Parses notice.log with note and msg fields."""
        rows = parse_zeek_log(str(analysis_dir_with_notices / "notice.log"))
        assert len(rows) == 1
        assert rows[0]["note"] == "BGP::HijackDetected"
        assert "Suspicious" in rows[0]["msg"]


# ---------------------------------------------------------------------------
# parse_all_logs
# ---------------------------------------------------------------------------


class TestParseAllLogs:
    def test_parses_all_log_files(self, analysis_dir: Path):
        """Parses every .log file in directory."""
        result = parse_all_logs(str(analysis_dir))
        assert "conn.log" in result
        assert "dns.log" in result
        assert "http.log" in result
        assert len(result) == 3

    def test_returns_rows_for_each(self, analysis_dir: Path):
        """Each log file maps to a list of row dicts."""
        result = parse_all_logs(str(analysis_dir))
        assert len(result["conn.log"]) == 3
        assert len(result["dns.log"]) == 2
        assert len(result["http.log"]) == 1

    def test_not_a_directory(self):
        """Non-directory path raises NotADirectoryError."""
        with pytest.raises(NotADirectoryError):
            parse_all_logs("/nonexistent/directory")

    def test_empty_directory(self, tmp_path: Path):
        """Directory with no .log files returns empty dict."""
        result = parse_all_logs(str(tmp_path))
        assert result == {}


# ---------------------------------------------------------------------------
# get_log_summary
# ---------------------------------------------------------------------------


class TestGetLogSummary:
    def test_summary_structure(self, analysis_dir: Path):
        """Summary returns file_count, files, and total_rows."""
        summary = get_log_summary(str(analysis_dir))
        assert summary["file_count"] == 3
        assert summary["total_rows"] == 6  # 3 conn + 2 dns + 1 http

    def test_per_file_info(self, analysis_dir: Path):
        """Each file entry has name, rows, and size_bytes."""
        summary = get_log_summary(str(analysis_dir))
        file_names = {f["name"] for f in summary["files"]}
        assert file_names == {"conn.log", "dns.log", "http.log"}

        for file_info in summary["files"]:
            assert "name" in file_info
            assert "rows" in file_info
            assert "size_bytes" in file_info
            assert file_info["size_bytes"] > 0

    def test_empty_log_summary(self, empty_analysis_dir: Path):
        """Summary of directory with empty log shows 0 rows."""
        summary = get_log_summary(str(empty_analysis_dir))
        assert summary["file_count"] == 1
        assert summary["total_rows"] == 0

    def test_not_a_directory(self):
        """Non-directory path raises NotADirectoryError."""
        with pytest.raises(NotADirectoryError):
            get_log_summary("/nonexistent/directory")


# ---------------------------------------------------------------------------
# filter_log
# ---------------------------------------------------------------------------


class TestFilterLog:
    def test_filter_by_ip(self, analysis_dir: Path):
        """Filter conn.log by source IP."""
        rows = filter_log(str(analysis_dir / "conn.log"), "id.orig_h", "192.168.1.10")
        assert len(rows) == 2
        assert all(r["id.orig_h"] == "192.168.1.10" for r in rows)

    def test_filter_by_service(self, analysis_dir: Path):
        """Filter conn.log by service name."""
        rows = filter_log(str(analysis_dir / "conn.log"), "service", "http")
        assert len(rows) == 1
        assert rows[0]["service"] == "http"

    def test_filter_case_insensitive(self, analysis_dir: Path):
        """Filter is case-insensitive substring match."""
        rows = filter_log(str(analysis_dir / "conn.log"), "service", "HTTP")
        assert len(rows) == 1

    def test_filter_substring_match(self, analysis_dir: Path):
        """Filter matches substrings, not just exact values."""
        rows = filter_log(str(analysis_dir / "dns.log"), "query", "example")
        assert len(rows) == 1
        assert rows[0]["query"] == "example.com"

    def test_filter_with_limit(self, analysis_dir: Path):
        """Limit parameter restricts filter results."""
        rows = filter_log(str(analysis_dir / "conn.log"), "proto", "tcp", limit=1)
        assert len(rows) == 1

    def test_filter_no_matches(self, analysis_dir: Path):
        """Filter with no matching rows returns empty list."""
        rows = filter_log(str(analysis_dir / "conn.log"), "service", "nonexistent")
        assert rows == []

    def test_filter_nonexistent_field(self, analysis_dir: Path):
        """Filtering on a field that does not exist returns empty list."""
        rows = filter_log(str(analysis_dir / "conn.log"), "no_such_field", "value")
        assert rows == []

    def test_filter_dns_query(self, analysis_dir: Path):
        """Filter dns.log for specific domain."""
        rows = filter_log(str(analysis_dir / "dns.log"), "query", "malware")
        assert len(rows) == 1
        assert rows[0]["rcode_name"] == "NXDOMAIN"


# ---------------------------------------------------------------------------
# get_connections_summary
# ---------------------------------------------------------------------------


class TestGetConnectionsSummary:
    def test_total_connections(self, analysis_dir: Path):
        """Summary reports correct total connection count."""
        summary = get_connections_summary(str(analysis_dir / "conn.log"))
        assert summary["total_connections"] == 3

    def test_byte_counts(self, analysis_dir: Path):
        """Summary accumulates originator and responder bytes."""
        summary = get_connections_summary(str(analysis_dir / "conn.log"))
        # 500 + 800 + 40 = 1340
        assert summary["total_orig_bytes"] == 1340
        # 1500 + 2400 + 120 = 4020
        assert summary["total_resp_bytes"] == 4020
        assert summary["total_bytes"] == 1340 + 4020

    def test_top_sources(self, analysis_dir: Path):
        """Top sources identifies the most active originator."""
        summary = get_connections_summary(str(analysis_dir / "conn.log"))
        assert "192.168.1.10" in summary["top_sources"]
        # 192.168.1.10 appears twice, 192.168.1.20 once
        assert summary["top_sources"]["192.168.1.10"] == 2

    def test_top_destinations(self, analysis_dir: Path):
        """Top destinations identifies the most contacted host."""
        summary = get_connections_summary(str(analysis_dir / "conn.log"))
        assert "10.0.0.1" in summary["top_destinations"]
        # 10.0.0.1 appears twice (http + dns)
        assert summary["top_destinations"]["10.0.0.1"] == 2

    def test_top_services(self, analysis_dir: Path):
        """Top services lists observed application protocols."""
        summary = get_connections_summary(str(analysis_dir / "conn.log"))
        assert "http" in summary["top_services"]
        assert "ssl" in summary["top_services"]
        assert "dns" in summary["top_services"]

    def test_protocol_counts(self, analysis_dir: Path):
        """Protocol counts include tcp and udp."""
        summary = get_connections_summary(str(analysis_dir / "conn.log"))
        assert summary["protocol_counts"]["tcp"] == 2
        assert summary["protocol_counts"]["udp"] == 1

    def test_file_not_found(self):
        """Missing conn.log raises FileNotFoundError."""
        with pytest.raises(FileNotFoundError):
            get_connections_summary("/nonexistent/conn.log")

    def test_empty_conn_log(self, empty_analysis_dir: Path):
        """Empty conn.log (no data rows) returns zero counts."""
        # Create a conn.log with no data rows
        conn = empty_analysis_dir / "conn.log"
        conn.write_text(
            "#separator \\x09\n"
            "#fields\tts\tuid\tid.orig_h\tid.resp_h\tservice\tproto\torig_bytes\tresp_bytes\n"
            "#types\ttime\tstring\taddr\taddr\tstring\tenum\tcount\tcount\n"
        )
        summary = get_connections_summary(str(conn))
        assert summary["total_connections"] == 0
        assert summary["total_bytes"] == 0
